## Epilogue

I've argued at length against the idea that conformity to one's own principles is a core part of ethics or epistemology. One should conform to good principles. If one's own principles are good, then one should conform to them. But that's because they are good, not because they are one's own.

One running theme of the book has been that the idea that we should conform to our principles leads to regresses. Philosophers like the idea that people should conform to their own principles because this often provides more useful, more actionable, advice than the idea that people should do what is right. But it isn't always more useful. Just as one might not know what the true principles are, one might not know how to apply principles one has chosen or adopted. So even if what matters is conformity to one's own principles, we can have disputes over who lives up to that standard. And if we want people to only be bound by constraints they can appreciate, indeed if that's why we thought conformity to one's own principles was so important, then we'll have to say that what matters is conformity to one's own judgment about what one's own principles requires. And now we're past the point at which subjectivism becomes implausible.

Another theme has been that the internalist wants beliefs to play philosophical roles that only desires are fit to play. The prudent person will perform acts that they believe will have consequences that they actually desire. They won't, in general, perform acts that they believe will have consequences that they believe they desire, or that they believe to be desirable, or that they believe to be valuable. All of these theories of prudence have only beliefs, and not desires, determine what is a prudent act, and hence are vulnerable to the technical objections to desire as belief theories. The moral person will desire things that are actually good. I think this means they will have a vast plurality of desires: to treat others with respect, to promote the general good, to keep their promises and contracts, and so on. What makes them moral is not that they have one desire, to do the good, plus some beliefs about what the good consists in; it is that they have the right desires. Similarly, the rational person will not have just one inferential disposition: to move from *it is rational to* ɸ *in my circumstances* to realizing ɸ. There is an internalist picture that this, plus very rich beliefs about what rationality consists in, is all the rational person needs. But this is not how the rational person should operate. Rather, they will have any number of distinct dispositions, corresponding to the various ways in which rationality requires one to react to different situations.

A final theme is more ironic. Internalism is often promoted as the theory that gives us moderation and caution. Some internalists in ethics describe their view as 'moral hedging'. Internalism in epistemology is motivated by cases like Christensen's medical resident, and disagreeing peers moving from extreme views to suspension of judgment. But nothing in the internalist's theory entails that they will always be on the side of moderation and caution. Indeed, a running theme of this part of the book has been the epistemological internalist will end up taking the extreme position in any number of cases. And internalism in ethics only makes sense if you think the good agent has as a primary aim, or perhaps as a sole aim, to do what is right by their own lights. And that is not a recipe for moderation and caution. Rather, it is the characteristic of that most immoderate and reckless figure: the self-righteous ideologue.

I don't object to aiming for caution and moderation in one's theory. But a lesson of the examples we've thought about in this book is that this must be inserted in first-order theory, not as the internalist wants to do in the meta-theory. My first-order suggestions are that we are thoroughly pluralist in our theory of value, and allow that mathematical investigation is a way of acquiring evidence, not processing it. But I'm less committed to those particular suggestions than I am to the view that imitating an ideologue is a bad way to promote moderation.

Amia Srinivasan ends her excellent paper "Normativity without Cartesian Privilege" by noting that her view, one that I'd call externalitist, "invites us to return to a more tragic outlook of the normative."  [@Srinivasan2015 287]. But that tragic outlook, she argues, can be beneficial; it helps focus on injustices in practice rather than injustices in theory.

The worldview motivating this book is very similar. Reflection on what makes tragic figures tragic is a good way to appreciate this worldview. (There is a reason I started this book by quoting Shakespeare.) And the misguided ideologue, the person who governs their thoughts and deeds by the theory they think is right, but in fact is off in one key respect, is one of the great tragic figures of modernity. What might have been a minor flaw in an average person becomes, in the ideologue, a character defining vice.

We should avoid that tragic end. We should try to live well and, if our minds turn to theory, we should try to have true beliefs about what it is to live well. If all goes perfectly, there will be a pleasing harmony between how we live and how we think one should live. But aiming for that harmony is dangerous, and changing our lives to guarantee it can bring more harm than good. And we should reject philosophical theories that draw conclusions about morality or rationality from giving that harmony too exalted a place.
